# Generated by Django 6.1.1 on 2026-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('goalkeeper', 'Portero'), ('defender', 'Defensa'), ('midfielder', 'Centrocampista'), ('forward', 'Delantero')], default='defender', max_length=20),
            preserve_default=False,
        ),
    ]
