# Generated by Django 6.1.1 on 2026-09-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
