# Generated by Django 6.1.1 on 2026-09-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_player_is_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='shirt_color',
            field=models.CharField(default='blanco', help_text='Color del uniforme del equipo (e.g., rojo, azul, verde)', max_length=20),
            preserve_default=False,
        ),
    ]
