# Generated by Django 6.1.1 on 2026-09-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_team_shirt_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Indica si este torneo es el predeterminado para la aplicación.'),
        ),
    ]
